dbt_thrive1_redshift_dw:
  target: dev
  outputs:
    dev:
      type: redshift
      host: "{{ env_var('REDSHIFT_HOST') }}"
      user: "{{ env_var('REDSHIFT_USER') }}"
      password: "{{ env_var('REDSHIFT_PASSWORD') }}"
      port: "{{ env_var('REDSHIFT_PORT') | int }}"
      dbname: "{{ env_var('REDSHIFT_DB') }}"
      schema: "{{ env_var('REDSHIFT_SCHEMA') }}"
      threads: 4
      sslmode: prefer
